### ISSUE TITLE
SwagPoints cannot center text

### ISSUE THREAD

**Issue by millytwm1228** [enginebai/SwagPoints#6]
-----
 <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"                 xmlns:swagpoints="http://schemas.android.com/apk/res-auto"                 android:layout_width="match_parent"                 android:layout_height="match_parent"                 android:background="@color/colorPrimary"     >      <android.support.v7.widget.Toolbar         android:id="@+id/toolbar"         android:layout_width="match_parent"         android:layout_height="wrap_content"         android:background="@color/colorPrimaryDark"         />      <com.dualcores.swagpoints.SwagPoints         android:layout_below="@+id/toolbar"         xmlns:swagpoints="http://schemas.android.com/apk/res-auto"         android:id="@+id/seekbar_point"         android:layout_width="match_parent"         android:layout_height="340dp"         android:layout_gravity="center"         android:padding="64dp"         swagpoints:min="100"         swagpoints:max="1000"         swagpoints:step="100"         swagpoints:progressColor="@color/color_progress"         swagpoints:progressWidth="12dp"         swagpoints:arcColor="@color/color_arc"         swagpoints:arcWidth="8dp"         swagpoints:textSize="72sp"         swagpoints:textColor="#ffffff"         swagpoints:indicatorIcon="@drawable/indicator"         />  </RelativeLayout>
-----
貼這段SwagPoints中間的字沒辦法置中

**Comment by enginebai** [comment]
This is fixed in `v1.0.1`, just update the dependency.
